###################################################################################################
#
# Configuration FrameGuard.
# license    LGPv3
# copyright  Copyright gorogoro.space 2021
# author     kubotan
# see        Kubotan's blog https://blog.gorogoro.space
#
###################################################################################################

# Debug mode
setting-debug-mode: false

# QueryTimeout
setting-query-timeout: 5

# Messages
message-enable: "The Plugin Has Been Enabled!"
message-disable: "The Plugin Has Been Disabled!"
message-command-reload: "Reload plugin."
message-command-enable: "Enable plugin."
message-command-disable: "Disable plugin."
message-locked: "Locked."
message-unlocked: "Unlocked"
message-information: "Output information."
message-can-not-lock-in-liquids: "Those in liquid can not be locked."
message-can-not-lock-hanging-place-is-liquid-or-air: "It can not be locked if the wall hanging place is liquid or air."
message-already-locked: "It is already locked."
message-no-lock-information: "There is no lock information."
message-lock-by-player: "__PLAYERNAME__ is locked."
message-block-is-locked: "This block is locked."
message-block-has-locked-wall-hanging: "There is a locked wall hanging."
message-execute-commands-from-chat: "I need to execute commands from chat!"
message-please-punch-the-target: "Please punch the target."
message-purge-the-data: "We have purged data older than __DAYS__ days."
