name: FrameGuard
version: 1.3
api-version: 1.15
description: FrameGuard plugin
author: kubotan
website: https://gorogoro.space/
main: space.gorogoro.frameguard.FrameGuard

commands:
  fglock:
    description: Lock a block using FrameGuard that only you can access
    usage: /<command>
  fgunlock:
    description: Remove a protection that was protected by FrameGuard
    usage: /<command> §7Enable FrameGuard
  fginfo:
    description: locked information.
    usage: /<command> §7View locked information by FrameGuard
  fgpurge:
    description: Purge data for FrameGuard
    usage: /<command> <days> §7Purge data for FrameGuard
  fgenable:
    description: enable FrameGuard
    usage: /<command> §7Enable FrameGuard
  fgdisable:
    description: disable FrameGuard
    usage: /<command> §7Disable FrameGuard
  fgreload:
    description: reload FrameGuard
    usage: /<command> §7Reload FrameGuard
